# Generated by Django 3.1.1 on 2021-09-10 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210910_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_autor', models.CharField(max_length=25)),
                ('comm_text', models.TextField()),
                ('comm_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
